language: python

python:
  - 2.7
  - 3.6
  - 3.7

install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget ${CONDA_BASE}2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls True
  - conda update --quiet conda
  - conda config --add channels conda-forge
  - ENV_NAME='test-environment'
  - conda create --name $ENV_NAME python=$TRAVIS_PYTHON_VERSION udunits2 --file requirements.txt --file requirements-dev.txt
  - source activate $ENV_NAME

  # Output debug info.
  - conda list
  - conda info -a

  # cf_units.
  - PREFIX=$HOME/miniconda/envs/$ENV_NAME

  - pip install -e .

script:
  - coverage run -m pytest cf_units cf_units

after_success: coveralls
