language: python

python:
  - 2.7
  - 3.6

install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget ${CONDA_BASE}2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda update --quiet conda
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

  # Customise the testing environment.
  # ----------------------------------
  - conda install --quiet udunits2 --file requirements.txt --file requirements-dev.txt
  - pip install coveralls

  # Output debug info.
  - conda list
  - conda info -a

  # cf_units.
  - PREFIX=$HOME/miniconda/envs/$ENV_NAME
  - SITE_CFG=cf_units/etc/site.cfg
  - echo "[System]" >> $SITE_CFG
  - echo "udunits2_path = $PREFIX/lib/libudunits2.so" >> $SITE_CFG

script:
  - coverage run setup.py test

after_success: coveralls
