language: minimal

env:
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7
  - PYTHON_VERSION=3.8

install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - if [[ "${PYTHON_VERSION}" == 2* ]]; then
      wget ${CONDA_BASE}2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls True
  - conda update --quiet conda
  - conda config --add channels conda-forge
  - ENV_NAME='test-environment'
 
  - conda create --name ${ENV_NAME} --quiet python=${PYTHON_VERSION} udunits2 pip
  - source activate ${ENV_NAME}
  - pip install -r requirements.txt -r requirements-dev.txt

  # Output debug info.
  - conda list -n ${ENV_NAME}
  - conda list -n ${ENV_NAME} --explicit
  - conda info -a

  # cf_units.
  - PREFIX=${HOME}/miniconda/envs/${ENV_NAME}
  - CYTHON_COVERAGE=1 pip install -e .

script:
  - pytest

after_success: coveralls
